# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Wx-Perl-Imagick
version:      0.02
version_from: lib\Wx\Perl\Imagick.pm
installdirs:  site
requires:
    Image::Magick:                 0
    Test::More:                    0
    Wx:                            0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
